name: Release

on:
  push:
    tags:
      - "v**.**.**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - run: npm version $VERSION --git-tag-version=false
      - run: yarn package-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/latest-linux.yml
            release/*.deb
            release/*.rpm
            release/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
